name: ${COMPOSE_PROJECT_NAME}

services:

  # Local LLM handler, for now only option to use application so always started
  ollama:
    image: ollama/ollama:latest
    container_name: ${COMPOSE_PROJECT_NAME}-ollama
    ports:
      - "${OLLAMA_PORT:-11434}:${OLLAMA_PORT:-11434}"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  # Service providing curated access to filesystem/db/APIs for the agent
  mcp-server:
      build:
        context: ${PWD}/mcp_server
        dockerfile: Dockerfile
      ports:
        # Warning: right side port must match port(s) exposed in DockerFile
        - "${MCP_SERVER_PORT:-8200}:${MCP_SERVER_PORT:-8200}"
      environment:
        - MCP_SERVER_PORT=${MCP_SERVER_PORT:-8200}
      restart: unless-stopped




volumes:
  ollama_data:
